openapi: 3.1.0
info:
  version: 1.0.0
  title: Orders & Products API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: REST API для управления заказами и связанными продуктами.

servers:
  - url: http://localhost:4000
    description: Local development server

security: []

tags:
  - name: Orders
    description: CRUD-операции над заказами и управление продуктами внутри заказа - поиск, фильтрация, удаление.
  - name: Products
    description: Операции с общим списком продуктов - поиск, фильтрация, удаление.

paths:
  /orders:
    get:
      $ref: "../swagger/paths/orders/get.yaml"
    post:
      $ref: "../swagger/paths/orders/post.yaml"
  /orders/{id}:
    get:
      $ref: "../swagger/paths/orders/{id}/get.yaml"
    delete:
      $ref: "../swagger/paths/orders/{id}/delete.yaml"
  /orders/{id}/products:
    get:
      $ref: "../swagger/paths/orders/{id}/products/get.yaml"
    post:
      $ref: "../swagger/paths/orders/{id}/products/post.yaml"
  /orders/{id}/products/{productId}:
    delete:
      $ref: "../swagger/paths/orders/{id}/products/{productId}/delete.yaml"
  /products:
    get:
      $ref: "../swagger/paths/products/get.yaml"
  /products/{id}:
    get:
      $ref: "../swagger/paths/products/{id}/get.yaml"
    delete:
      $ref: "../swagger/paths/products/{id}/delete.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
